Path Of Titans
pelican-eggs/eggs pull request #2872
Opened 2024-04-07 20:00 UTC by Hendalf-DEV

Path Of Titans server egg. Not tested properly but the server is running so I guess it works if you set all the required ports.

# Description

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [] Have you tested and reviewed your changes with confidence that everything works?
* [] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
  I'm adding not editing, so there is no need to have backup of anything.

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [X] If some script is needed then it is part of a current yolk or a PR to add one
6. [ ] The egg was exported from the panel

2024-04-10 20:38 UTC, SulivanM commented
Hello there,
I got an error installation : 
![image](https://github.com/parkervcp/eggs/assets/139988886/f34a0372-bfd4-47a9-8f80-bb1820350d60)

Best regards

2024-04-25 08:50 UTC, Hendalf-DEV commented
> Hello there, I got an error installation : ![image](https://private-user-images.githubusercontent.com/139988886/321397159-f34a0372-bfd4-47a9-8f80-bb1820350d60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzUyNTUsIm5iZiI6MTcxNDAzNDk1NSwicGF0aCI6Ii8xMzk5ODg4ODYvMzIxMzk3MTU5LWYzNGEwMzcyLWJmZDQtNDdhOS04ZjgwLWJiMTgyMDM1MGQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODQ5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDNiZjA3YTY5OGI4NzFhYTFkZDdkNDkxYzczY2IzYzk5NGE1MWMzZGEyMjk4NjFhNjM1NjRlMjUxNWI5OThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f2iO007V8jX1bpr3AFOOZg3ZMKgR3upYEeK4OWmpAfM)
> 
> Best regards

Hello, sorry for long response, I am currentyly going to test this again, but I need time.

With kind regards, Hendalf

2024-04-25 08:56 UTC, gOOvER commented
> Hello there, I got an error installation : ![image](https://private-user-images.githubusercontent.com/139988886/321397159-f34a0372-bfd4-47a9-8f80-bb1820350d60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU2NzQsIm5iZiI6MTcxNDAzNTM3NCwicGF0aCI6Ii8xMzk5ODg4ODYvMzIxMzk3MTU5LWYzNGEwMzcyLWJmZDQtNDdhOS04ZjgwLWJiMTgyMDM1MGQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODU2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWExOTU4ZTI1NGFlNzA5OWQ3Yzc1NjBlZTVlNjZkNGE3YmFiY2U4OTRmNDk4Y2Y4YzI4MDIwMjU2MWU2MTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6E30KDb30AHd5Rc_bKN9GKftiCi3ejwP3Q8O2Gv6xQ)
> 
> Best regards

add this as variable or define it in the image

2024-04-25 09:45 UTC, Hendalf-DEV commented
Hello again, I found the issue. It seems that POT does not want to run on Ubuntu image for some reason. So I reccomend change it to Debian image. That should work.

With kind regards, Hendalf.

p.s. I am going to make changes to this egg so no one will get to this trap again.

2024-04-25 09:50 UTC, Hendalf-DEV commented
Providing additional images
![image](https://github.com/pelican-eggs/eggs/assets/56977415/e7ffe0cb-846a-4ccc-b6b8-30bc56c81e7e)

2024-04-25 09:56 UTC, Hendalf-DEV commented
The only thing that is additionally required is some of the ports
If there is possibility to make them accessable for the server without adding them additionally, it would be nice.

![image](https://github.com/pelican-eggs/eggs/assets/56977415/ab68191c-0408-4871-8d95-33e000769937)

2024-04-25 09:57 UTC, gOOvER commented
> The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> 
> ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)

you can only autoassign the primary port. For all others you must add variables

2024-04-25 10:08 UTC, Hendalf-DEV commented
> > Hello again, I found the issue. It seems that POT does not want to run on Ubuntu image for some reason. So I reccomend change it to Debian image. That should work.
> > With kind regards, Hendalf.
> > p.s. I am going to make changes to this egg so no one will get to this trap again.
> 
> Somehow I can't believe that now? Do you have an error message why it doesn't work with Ubuntu?

Nope, it just gives the same thing as this person had, I changed to Debian and now it works.

2024-04-25 10:10 UTC, Hendalf-DEV commented
> > The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> > ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)
> 
> you can only autoassign the primary port. For all others you must add variables

Atleast I got the query port assigned automatically. But I have no clue about how do I assign rcon port.

2024-04-25 10:12 UTC, gOOvER commented
> > > The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> > > ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)
> > 
> > 
> > you can only autoassign the primary port. For all others you must add variables
> 
> Atleast I got the query port assigned automatically. But I have no clue about how do I assign rcon port.

there is only 1 variable which is autoassigned: SERVER_PORT.

For all others you must add a varibale, so i dont believe that Queryport was autoassigned, when there is no variable

2024-04-25 10:14 UTC, gOOvER commented
> > > Hello again, I found the issue. It seems that POT does not want to run on Ubuntu image for some reason. So I reccomend change it to Debian image. That should work.
> > > With kind regards, Hendalf.
> > > p.s. I am going to make changes to this egg so no one will get to this trap again.
> > 
> > 
> > Somehow I can't believe that now? Do you have an error message why it doesn't work with Ubuntu?
> 
> Nope, it just gives the same thing as this person had, I changed to Debian and now it works.

thats not a problem with the Distro. Which image are you using now?

If steamcmd, then Dotnet is allready installed. In Ubuntu it isnt

2024-04-25 10:14 UTC, Hendalf-DEV commented
> > > > The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> > > > ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)
> > > 
> > > 
> > > you can only autoassign the primary port. For all others you must add variables
> > 
> > 
> > Atleast I got the query port assigned automatically. But I have no clue about how do I assign rcon port.
> 
> there is only 1 variable which is autoassigned: SERVER_PORT.
> 
> For all others you must add a varibale, so i dont believe that Queryport was autoassigned, when there is no variable

I guess I made it unclear what I did mean by that. Asssigning screenshot.
I added server properties to the config file.

![image](https://github.com/pelican-eggs/eggs/assets/56977415/b23ba74e-8d3c-4c1d-aed4-4c08f0b25cdc)

2024-04-25 10:15 UTC, gOOvER commented
> > > > > The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> > > > > ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)
> > > > 
> > > > 
> > > > you can only autoassign the primary port. For all others you must add variables
> > > 
> > > 
> > > Atleast I got the query port assigned automatically. But I have no clue about how do I assign rcon port.
> > 
> > 
> > there is only 1 variable which is autoassigned: SERVER_PORT.
> > For all others you must add a varibale, so i dont believe that Queryport was autoassigned, when there is no variable
> 
> I guess I made it unclear what I did mean by that. Asssigning screenshot. I added server properties to the config file.
> 
> ![image](https://private-user-images.githubusercontent.com/56977415/325566337-b23ba74e-8d3c-4c1d-aed4-4c08f0b25cdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDAzODAsIm5iZiI6MTcxNDA0MDA4MCwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjYzMzctYjIzYmE3NGUtOGQzYy00YzFkLWFlZDQtNGMwOGYwYjI1Y2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOTE5ZGM4NTNiODk1MzdhNjZmM2RkNmNkNDFmMWNmOWUwZWM2YTc0ZTVjYzRhYzNmYTBiZGU2OWUwNmVkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nal3SK63WleYyt88WlKbUS8hk6gz_-yuXpP3-rC1M_g)

sry, but this is a hardcoded Port and this will never be added here

2024-04-25 10:15 UTC, Hendalf-DEV commented
> > > > Hello again, I found the issue. It seems that POT does not want to run on Ubuntu image for some reason. So I reccomend change it to Debian image. That should work.
> > > > With kind regards, Hendalf.
> > > > p.s. I am going to make changes to this egg so no one will get to this trap again.
> > > 
> > > 
> > > Somehow I can't believe that now? Do you have an error message why it doesn't work with Ubuntu?
> > 
> > 
> > Nope, it just gives the same thing as this person had, I changed to Debian and now it works.
> 
> thats not a problem with the Distro. Which image are you using now?
> 
> If steamcmd, then Dotnet is allready installed. In Ubuntu it isnt

Ok, that makes sense. I use the ghcr.io/parkervcp/yolks:debian

2024-04-25 10:16 UTC, Hendalf-DEV commented
> > > > > > The only thing that is additionally required is some of the ports If there is possibility to make them accessable for the server without adding them additionally, it would be nice.
> > > > > > ![image](https://private-user-images.githubusercontent.com/56977415/325560770-ab68191c-0408-4871-8d95-33e000769937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzkzMTEsIm5iZiI6MTcxNDAzOTAxMSwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjA3NzAtYWI2ODE5MWMtMDQwOC00ODcxLThkOTUtMzNlMDAwNzY5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWNlMDRjNmE0ZWE3NTFiNGRiMzgzNThlM2Q1YTU2NGY4OWJkNTJiMmE3MmMwZGZiN2ExMTNmMWYwOGMzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wqs7ttysNf8aiqX6aKu9N_M028P5Xbj2bClQUnZfUSU)
> > > > > 
> > > > > 
> > > > > you can only autoassign the primary port. For all others you must add variables
> > > > 
> > > > 
> > > > Atleast I got the query port assigned automatically. But I have no clue about how do I assign rcon port.
> > > 
> > > 
> > > there is only 1 variable which is autoassigned: SERVER_PORT.
> > > For all others you must add a varibale, so i dont believe that Queryport was autoassigned, when there is no variable
> > 
> > 
> > I guess I made it unclear what I did mean by that. Asssigning screenshot. I added server properties to the config file.
> > ![image](https://private-user-images.githubusercontent.com/56977415/325566337-b23ba74e-8d3c-4c1d-aed4-4c08f0b25cdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDAzODAsIm5iZiI6MTcxNDA0MDA4MCwicGF0aCI6Ii81Njk3NzQxNS8zMjU1NjYzMzctYjIzYmE3NGUtOGQzYy00YzFkLWFlZDQtNGMwOGYwYjI1Y2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOTE5ZGM4NTNiODk1MzdhNjZmM2RkNmNkNDFmMWNmOWUwZWM2YTc0ZTVjYzRhYzNmYTBiZGU2OWUwNmVkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nal3SK63WleYyt88WlKbUS8hk6gz_-yuXpP3-rC1M_g)
> 
> sry, but this is a hardcoded Port and this will never be added here

My english could be a little bit worse, but I did not understand what did you mean by hardcoded port and what will not be added?

2024-04-25 16:24 UTC, That411Guy commented
If you want I have a fully working egg for this game that I made

2024-04-26 05:45 UTC, Hendalf-DEV commented
> If you want I have a fully working egg for this game that I made

This egg does work, so no need, thank you.

2024-04-26 06:46 UTC, Hendalf-DEV reviewed
All required changes are made, now need to test only the connection, and thats all.

2024-04-26 06:51 UTC, gOOvER requested changes

2024-04-26 06:51 UTC, gOOvER commented on game_eggs/path_of_titans/egg-path-of-titans.json
> +        "files": "{\r\n    \"server.properties\": {\r\n        \"parser\": \"properties\",\r\n        \"find\": {\r\n            \"server-ip\": \"0.0.0.0\",\r\n            \"enable-query\": \"true\",
Port 7778 is hardcoded and this cant work, when the port is allready assigned in an other server. As i told you, add a variable for this port

2024-04-26 17:11 UTC, Hendalf-DEV commented
Server connectable
![image](https://github.com/pelican-eggs/eggs/assets/56977415/b4e7d192-5e93-4ea3-88e4-eca16a89ebda)

2024-04-29 04:09 UTC, Hendalf-DEV commented
Stull awaiting review

2024-04-29 06:18 UTC, QuintenQVD0 commented
No pr will be merged to this repo as it soon will become read only. Please move your pr to the right repo on this organization as all eggs catogories now have their own repo.

2024-04-29 06:26 UTC, Hendalf-DEV commented
> No pr will be merged to this repo as it soon will become read only. Please move your pr to the right repo on this organization as all eggs catogories now have their own repo.

Which repo is the right one?

2024-04-29 06:42 UTC, Hendalf-DEV commented
Nevermind, I guess I found the one which is right one https://github.com/pelican-eggs/games. Atleast I hope it's the right one.

2024-04-29 06:42 UTC, closed without merging

2024-04-29 07:09 UTC, QuintenQVD0 commented
> Nevermind, I guess I found the one which is right one https://github.com/pelican-eggs/games. Atleast I hope it's the right one.

That is indeed the right one for this PR